### ISSUE TITLE
Logic Explanation

### ISSUE THREAD

**Issue by mehtayash23** [nilotpal9797/MorganStanleyCodeAthon#1]
Hi Nilotpal,
Thanks for sharing this.
Can you please explain the logic that you have used here?

**Comment by nilotpal9797** [comment]
@mehtayash23 The codes are pretty easy to understand and I dont even remember the questions now.I posted this a long time back and you can certainly figure out the logic from the code.Thanks.

**Comment by mehtayash23** [comment]
Yes, I figured it out. :)
